FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl unzip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Ngrok installation
RUN curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip && \
    unzip ngrok.zip && \
    mv ngrok /usr/local/bin && \
    rm ngrok.zip


WORKDIR /app
COPY . .

RUN chmod +x scripts/serve_and_tunnel.sh

EXPOSE 8000

# Entry point
CMD ["./scripts/serve_and_tunnel.sh"]