FROM python:3.10-slim

RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copier les fichiers
COPY . /app

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Exposer le port de l'API
EXPOSE 8000

# Lancer FastAPI
CMD ["uvicorn", "scripts.app:app", "--host", "0.0.0.0", "--port", "8000"]
